version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-gerenciadorfinancas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: abc1234
      MYSQL_DATABASE: gerenciadorfinancas
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: